<!DOCTYPE html>
<html lang="es">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <!--
        Los distintos tipos de datos númericos que podemos encontrar en php, ya sabemos que tipo de datos númericos existen pero que pasa
        cuando queremos imprimir el valor del tipo de dato que se encuentra en una variable para eso usaremos el comado de var_dump que 
        sera capaz de mostrar el tipo de valor que le asignamos a la variable.

            Ejemplo:
        usaremos un integer o número entero 

        $inter = 10;
            var_dump($inter);
    -->

    <body>
        <?php
        #Ejemplo Número 1: Usaremos un dato de tipo integer para este primer ejemplo 
        ?>
    </body>
</html>