<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Laboratorio 1</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <!--
        Este es el primer laboratorio de pruebas que se realiza con todo lo aprendido hasta ahora. Se estarán presentando operaciones básicas
        arítmeticas con lo que se a aprendido hasta el momento.

        Criterios de Laboratirio:
            1.Debe de contener  
                Suma
                Resta
                Multiplicación
                Divición
            2.Debe contener
                Variables
                Constantes
                Comentarios
                Funciones de strign
            3.Debe de ser presentable y funcional.
            4.Se bede evidenciar
                Ubicación de PHP
                Variables
                Concatenación
                Comentarios
                Saltos de lineas 
                Print / echo
                Funciones de string (Cualquiera minimo 2)
                datos númericos
                constanes

    -->
    <body>
        <?php
        #Usamos una constante para la imprimir valores fijos como interacciones 
        define ("INI_PRO","Demos tración de operaciones basicas arítmerticas con php."."<br>");
            Echo INI_PRO ;

        #iniciamos con la suma
        ?>
    </body>
</html>